name: Go
on: [push]
jobs:

  test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:

    - uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - uses: actions/checkout@v1

    - name: test
      run: |
        go get github.com/ysmood/kit/cmd/godev
        go generate
        go test
