name: Go
on: [push]
jobs:

  test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:

    - uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Set git to use LF
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - uses: actions/checkout@v2

    - name: test
      run: |
        cd ..
        go get github.com/ysmood/kit/cmd/godev
        cd leakless
        go generate
        go test
